### ISSUE TITLE
Composer not pulling package

### ISSUE THREAD

**Issue by Peace-N** [o-ba/covid-php#1]
I have a strange issue, composer is not pulling the package when i run:

λ composer require o-ba/covid-php

There is no change >>

**Comment by o-ba** [comment]
What error do you get? Have you already tired to flush composer cache?

`composer clearcache`

**Comment by Peace-N** [comment]
Ok thanks so much, that worked . How often do you update your data ??

**Comment by o-ba** [comment]
Great.
